<br>
    
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
                            
					<li class="active">
					<a href=<?=$this->baseUrl()?>/categories/list>Home</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/showprofile>Profile</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/choosereceiver>Send Message</a>
				</li>
                                
                                <li class="dropdown pull-right">
					 <a href="/zendapp/public/user/logout" >Log Out</a>
					
				</li>
                                
                                
			</ul>
                </div>
        </div>
		
</div>
<br><br>

        <div class="row">
                      <div class='col-md-12'>
                          <ul class="nav nav-pills">
           <?php              
                    if($this->type==1){
                       
                       // echo "email ".$this->type;
                             echo " <li class=active><a href=".$this->baseUrl()."/categories/add>Add Category</a></li>";
                    } 
           ?>
                          </ul>
                      </div>
            </div>

<div class="container-fluid" style="float:right;">
	<div class="row-fluid" style="float:right;">
		<div class="span12" style="float:right;">
                    <?php
                        if($this->type==1){
			echo "<ul class=nav nav-list>";
				echo "<li class=nav-header>
					List Options
				</li>
				<li class=active>
					<a href=".$this->baseUrl()."/categories/list>Category</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/forums/list>Forum</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/posts/list>Post</a>
				</li>
				
				<li>
					<a href=".$this->baseUrl()."/comments/list>Comment</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/user/listusers>user</a>
				</li>
			</ul>";
                        }
                     ?>
		</div>
	</div>
</div>
 
       
    <?php
       // echo count($this->categories);
        //print_r($this->categories);
        echo "<br>";
        $i=1;
        echo "<table class=table id=catTable>";
        echo "<tr class=Danger>";
        echo "<td>category</td>";
        if($this->type==1){
            echo "<td>edit</td>";
            echo "<td>delete</td>";
        }
        echo "</tr>";
        foreach ($this->categories as $row){
            
           echo "<tr>";
           echo "<td id=n".$row['c_id']."><a href=http://localhost".$this->baseUrl()."/forums/listsepecific/catid/".$row['c_id'].">".$row['name']."</a></td>";
            if($this->type==1){
                echo "<td> <a href=".$this->baseUrl()."/categories/edit/catid/".$row['c_id']."><img src=".$this->baseUrl()."/images/edit.jpg width=42 height=25></a></td>";
                //echo "<td> <a href=delete/catid/".$row['c_id']."><img src=".$this->baseUrl()."/images/delete.jpg width=42 height=25></a></td>";
                echo "<td> <a onClick= delet(".$row['c_id'].",".$i.")><img src=".$this->baseUrl()."/images/delete.jpg width=42 height=25></a></td>";

                    $i++;
            }
        }
       echo "</table>";
    ?>


    <script>
	var ajaxRequest;
	ajaxRequest=new XMLHttpRequest();

	function delet (id,i){
		var ajaxRequest;
		if (window.XMLHttpRequest){
			ajaxRequest=new XMLHttpRequest();
		}
		else{
			ajaxRequest=new ActiveXObject("Microsoft.XMLHTTP");
		}
		var name;
		name=document.getElementById('n'+id).value;
		ajaxRequest.onreadystatechange=function(){
			//console.log(ajaxRequest.readyState);
			//console.log(ajaxRequest.readyState);
			if (ajaxRequest.readyState==4){
				document.getElementById("catTable").deleteRow(i);
			}	
		}
		//var parameters="name="+name+"&id="+id;
		ajaxRequest.open("GET", "delete?catid="+id, true);
		//ajaxRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		ajaxRequest.send(null);
	
	}
        </script>