
<br>
    
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
                            
				<li class="active">
					<a href=<?=$this->baseUrl()?>/categories/list>Home</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/showprofile>Profile</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/choosereceiver>Send Message</a>
				</li>
                                
                                <li class="dropdown pull-right">
					 <a href="/zendapp/public/user/logout" >Log Out</a>
					
				</li>
                                
                                
			</ul>
                </div>
        </div>
		
</div>
<br> <br><br><br>

<div class="container-fluid" style="float:right;">
	<div class="row-fluid" style="float:right;">
		<div class="span12" style="float:right;">
                    <?php
                        if($this->type==1){
			echo "<ul class=nav nav-list>";
				echo "<li class=nav-header>
					List Options
				</li>
				<li class=active>
					<a href=".$this->baseUrl()."/categories/list>Category</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/forums/list>Forum</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/posts/list>Post</a>
				</li>
				
				<li>
					<a href=".$this->baseUrl()."/comments/list>Comment</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/user/listusers>user</a>
				</li>
			</ul>";
                        }
                     ?>
		</div>
	</div>
</div>
<?php
    echo "<form method=post>";
    echo "<fieldset >";
    echo "<legend > <font size=6>Edit Post:</font></legend>";
    $this->posts ->populate($this->post);
    //echo $this->posts->name;
    echo "<p><img src=".$this->img.".jpg width=60 height=60>&emsp;<input type=text value=".$this->name." readonly style=border:none;></p>";
    echo "<font size=4>".$this->posts->title."</font>";
    echo "<font size=4>".$this->posts->post."</font>";
    echo "<font size=4>".$this->posts->f_name."</font>";
    
    echo "<br><font size=4> <strong> Change Forum:</strong></font><br>";
    echo "&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;";
        echo "<select name=changeForum style=width:150px;height:30px;>";
        foreach ($this->allForums as $row){
            if($this->forumId==$row['f_id']||$this->fId==$row['f_id']){
               echo "<option selected value=".$row['f_id'].">".$row['f_name']."</option>"; 
            }
            else{
                echo "<option value=".$row['f_id'].">".$row['f_name']."</option>";
            }
                     
        }  
        echo "</select>";
         echo "</br>";
          if($this->type==1){
            echo "<font size=4>".$this->posts->p_flag."</font>";
    
            echo "<br><font size=4> <strong> Change Loack: </strong></font><br>";
            echo "&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;"
            . "<select name=changeBan style=width:150px;height:30px;>".
                "<option value=unlock>unlock</option>".
                "<option value=lock>lock</option>".
            "</select><br>";
     }
         echo "</fieldset>";
        echo "<font size=4>".$this->posts->submit."</font>";
       
    echo "</form>";
    ?>

 