

<br>
    
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
                            
				<li class="active">
					<a href=<?=$this->baseUrl()?>/categories/list>Home</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/showprofile>Profile</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/choosereceiver>Send Message</a>
				</li>
                                
                                <li class="dropdown pull-right">
					 <a href="/zendapp/public/user/logout" >Log Out</a>
					
				</li>
                                
                                
			</ul>
                </div>
        </div>
		
</div>
<br> <br>
 <div class="row">
                <div class="col-md-12">
                    <ul class="nav nav-pills">
                        <li class="active"><a href=<?=$this->baseUrl()?>/posts/add/forumId/<?=$this->forumId?>>Add Post</a></li>
                    </ul>
                </div>
      </div>



<br />
<div class="container-fluid" style="float:right;">
	<div class="row-fluid" style="float:right;">
		<div class="span12" style="float:right;">
                    <?php
                        if($this->type==1){
			echo "<ul class=nav nav-list>";
				echo "<li class=nav-header>
					List Options
				</li>
				<li class=active>
					<a href=".$this->baseUrl()."/categories/list>Category</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/forums/list>Forum</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/posts/list>Post</a>
				</li>
				
				<li>
					<a href=".$this->baseUrl()."/comments/list>Comment</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/user/listusers>user</a>
				</li>
			</ul>";
                        }
                     ?>
		</div>
	</div>
</div>
    

<?php
       // echo count($this->categories);
        //print_r($this->categories);
        $tableno=1;
        $checkid=0;
        $baseurl=$this->baseUrl();
        //print_r ($this->stickies);
        //echo "<input type=text value=".$baseurl.">";
        //echo $this->forums;
        //echo $this->threads;
        foreach ($this->forums as $dis){
            $i=1;
            $stid=0;
            
            echo "<h3><u>Forum Name:</u>&nbsp;&nbsp;&nbsp;&nbsp;".$dis['f_name']."</h3>";
            echo "<br> ";
            echo "<table class=table  id=postTable".$tableno.">";
            echo "<tr class=Danger>";
            echo "<td>post title</td>";
            echo "<td>edit</td>";
            echo "<td>delete</td>";
            /*foreach ($this->stickies as $stick){
                if ($dis['f_id']==$stick['forum_f_id']){
                    echo "<br> sticky post:<input type=text value='".$stick['title']."'>";   
                }
            }*/
                if ($this->type==1){
                    echo "<td> sticky post</td>";
                }
            echo "</tr>";
            foreach ($this->threads as $row){
                if($dis['f_id']==$row['forum_f_id']){
                    echo "<tr>";
                    echo "<td id=n".$row['p_id']."> <a href=http://localhost".$this->baseUrl()."/posts/showpost/postid/".$row['p_id'].">".$row['title']."</a> </td>";
                    if ($this->uid==$row['user_u_id']||$this->type==1){
                            echo "<td> <a href=http://localhost".$this->baseUrl()."/posts/edit/postid/".$row['p_id']."/fId/".$row['forum_f_id']."><img src=".$this->baseUrl()."/images/edit.jpg width=35 height=20></a></td>";
                            echo "<td> <a onClick= delet(".$row['p_id'].",".$i.",".$tableno.")><img src=".$this->baseUrl()."/images/delete.jpg width=35 height=20></a></td>";
                    }
                    else{
                            echo "<td> </td>";
                            echo "<td> </td>";
                    }
                     if ($row['sticky']==1&&$this->type==1){
                //echo $this->type;
                        echo "<td><input type=checkbox id=sti".$row['p_id']." checked onClick=newuncheck(".$row['p_id'].",".$row['forum_f_id'].",'".$baseurl."')><a></a</td>";

                    }
                    elseif ($row['sticky']==0&&$this->type==1){
                        //echo $this->type;
                                echo "<td> <input type=checkbox id=sti".$row['p_id']." onClick=newcheck(".$row['p_id'].",".$row['forum_f_id'].",'".$baseurl."')></td>";                        
                    }
                        $i++;
                }
            }
            $tableno++;
            echo "</fieldset>";
            echo "</table>";
        }
    ?>

<script>
	var ajaxRequest;
	ajaxRequest=new XMLHttpRequest();
        
        
        function newcheck(chid,fid,b){
            
            window.location.assign("http://localhost"+b+"/posts/sticky/check/"+chid+"/uncheck/"+fid);
        }
        
        function newuncheck(chid,b){
            
            window.location.assign("http://localhost"+b+"/posts/unsticky/uncheck/"+chid);
        }
        
	function delet (id,i,t){
		//var ajaxRequest;
		if (window.XMLHttpRequest){
			ajaxRequest=new XMLHttpRequest();
		}
		else{
			ajaxRequest=new ActiveXObject("Microsoft.XMLHTTP");
		}
		var name;
		name=document.getElementById('n'+id).value;
		ajaxRequest.onreadystatechange=function(){
			if (ajaxRequest.readyState==4){
				document.getElementById("postTable"+t).deleteRow(i);
			}	
		}
		//var parameters="name="+name+"&id="+id;
		ajaxRequest.open("GET","http://localhost/zendapp/public/posts/delete?postid="+id, true);
		//ajaxRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		ajaxRequest.send(null);
	
	}
        
        
	function stick (cid,fid){
            //alert ("heloo");
            //alert (cid);
           // alert (uni);
            //alert (uncid);
            
		//var ajaxRequest;
		if (window.XMLHttpRequest){
			ajaxRequest=new XMLHttpRequest();
		}
		else{
			ajaxRequest=new ActiveXObject("Microsoft.XMLHTTP");
		}
		var check;
                var uncheck;
		/*check=document.getElementById('sti'+t+i);
                if (uni>0){
                     console.log (document.getElementById('sti'+t+uni));
                    uncheck=document.getElementById('sti'+t+uni);
                   
                }*/
                console .log(ajaxRequest.readyState);
		ajaxRequest.onreadystatechange=function(){
			if (ajaxRequest.readyState==4){
                            console .log(ajaxRequest.readyState);
                            console.log(ajaxRequest.responseText);
                            /*alert (uncid);
				check.checked=true;
                                
                                if (uni>0){
                                    uncheck.checked=false;
                                }*/
			}	
		}
		//var parameters="postid="+cid+"&forumid="+fid;
               // console.log("http://localhost/zendapp/public/posts/sticky?cpostid="+cid+"&uncpostid"+uncid");
		ajaxRequest.open("GET","http://localhost/zendapp/public/posts/sticky", true);
		//ajaxRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		ajaxRequest.send(null);
	
	}
        </script>