
<br>
    
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
                            
				<li class="active">
					<a href=<?=$this->baseUrl()?>/categories/list>Home</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/showprofile>Profile</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/choosereceiver>Send Message</a>
				</li>
                                
                                <li class="dropdown pull-right">
					 <a href="/zendapp/public/user/logout" >Log Out</a>
					
				</li>
                                
                                
			</ul>
                </div>
        </div>
		
</div>
<br> <br>
 <div class="row">
                <div class="col-md-12">
                    <ul class="nav nav-pills">
                    <?php              
                        if($this->lock=='unlock'||$this->type==1){

                           // echo "email ".$this->type;
                                 echo "<li class=active><a href=".$this->baseUrl()."/posts/add/forumId/".$this->forumId.">Add Post</a></li>";
                        }  
                    ?>
                    </ul>
                </div>
      </div>



<br />
<div class="container-fluid" style="float:right;">
	<div class="row-fluid" style="float:right;">
		<div class="span12" style="float:right;">
                    <?php
                        if($this->type==1){
			echo "<ul class=nav nav-list>";
				echo "<li class=nav-header>
					List Options
				</li>
				<li class=active>
					<a href=".$this->baseUrl()."/categories/list>Category</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/forums/list>Forum</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/posts/list>Post</a>
				</li>
				
				<li>
					<a href=".$this->baseUrl()."/comments/list>Comment</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/user/listusers>user</a>
				</li>
			</ul>";
                        }
                     ?>
		</div>
	</div>
</div>
    
          
                    

      
<?php
       // echo count($this->categories);
        //print_r($this->categories);
       
        echo "<h3><u>Forum Name:</u> &nbsp;&nbsp;&nbsp;".$this->forumName."</h3>";
        $i=1;
        $baseurl=$this->baseUrl();
        echo "<br>"; 
        echo "<table class=table id=postTable>";
        echo "<tr class=Danger>";
        echo "<td >post title</td>";
        echo "<td>edit</td>";
        echo "<td>delete</td>";
         if ($this->type==1){
                echo "<td>sticky post</td>";
         }
        echo "</tr>";
        foreach ($this->threads as $row){
            
           echo "<tr>";
                    
           echo "<td id=n".$row['p_id']."> <a href=http://localhost".$this->baseUrl()."/posts/showpost/postid/".$row['p_id'].">".$row['title'].$this->uid."</a> </td>";
           if ($this->uid==$row['user_u_id']||$this->type==1){
                // echo $this->type;
                echo "<td> <a href=http://localhost".$this->baseUrl()."/posts/edit/postid/".$row['p_id']."/forumId/".$row['forum_f_id']."><img src=".$this->baseUrl()."/images/edit.jpg width=42 height=25></a></td>";
                echo "<td> <a onClick= delet(".$row['p_id'].",".$i.")><img src=".$this->baseUrl()."/images/delete.jpg width=42 height=25></a></td>";
           }
            else{
                            echo "<td> </td>";
                            echo "<td> </td>";
            }
            if ($row['sticky']==1&&$this->type==1){
                //echo $this->type;
                        echo "<td><input type=checkbox id=sti".$row['p_id']." checked onClick=newuncheck(".$row['p_id'].",".$row['forum_f_id'].",'".$baseurl."')><a></a</td>";

                    }
            elseif ($row['sticky']==0&&$this->type==1){
                //echo $this->type;
                        echo "<td> <input type=checkbox id=sti".$row['p_id']." onClick=newcheck(".$row['p_id'].",".$row['forum_f_id'].",'".$baseurl."')></td>";                        
            }
        }
           $i++;
        
        echo "</table>";
    ?>

<script>
	var ajaxRequest;
	ajaxRequest=new XMLHttpRequest();

	function delet (id,i){
		var ajaxRequest;
		if (window.XMLHttpRequest){
			ajaxRequest=new XMLHttpRequest();
		}
		else{
			ajaxRequest=new ActiveXObject("Microsoft.XMLHTTP");
		}
		var name;
		name=document.getElementById('n'+id).value;
		ajaxRequest.onreadystatechange=function(){
			if (ajaxRequest.readyState==4){
				document.getElementById("postTable").deleteRow(i);
			}	
		}
		//var parameters="name="+name+"&id="+id;
		ajaxRequest.open("GET","http://localhost/zendapp/public/posts/delete?postid="+id, true);
		//ajaxRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		ajaxRequest.send(null);
	
	}
        function newcheck(chid,fid,b){
            
            window.location.assign("http://localhost"+b+"/posts/sticky/check/"+chid+"/uncheck/"+fid+"/listspecify/yes");
        }
        
        function newuncheck(chid,fid,b){
//window.location.assign("http://www.w3schools.com");
           window.location.assign("http://localhost"+b+"/posts/unsticky/uncheck/"+chid+"/forumid/"+fid+"/listspecify/yes");
        }
        </script>