
<br>

<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
                            
				<li class="active">
					<a href=<?=$this->baseUrl()?>/categories/list>Home</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/showprofile>Profile</a>
				</li>
                                
                               
                                
                                <li class="dropdown pull-right">
					 <a href="/zendapp/public/user/logout" >Log Out</a>
					
				</li>
                                
                                
			</ul>
                </div>
        </div>
		
</div>
<br><br>

  
        <div class="row">
                      <div class='col-md-12'>
                          <ul class="nav nav-pills">
                          </ul>
                                                       
<div class="container-fluid" style="float:right;">
	<div class="row-fluid" style="float:right;">
		<div class="span12" style="float:right;">
                    <?php
                        if($this->type==1){
			echo "<ul class=nav nav-list>";
				echo "<li class=nav-header>
					List Options
				</li>
				<li class=active>
					<a href=".$this->baseUrl()."/categories/list>Category</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/forums/list>Forum</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/posts/list>Post</a>
				</li>
				
				<li>
					<a href=".$this->baseUrl()."/comments/list>Comment</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/user/listusers>user</a>
				</li>
			</ul>";
                        }
                     ?>
		</div>
	</div>
</div>

<?php

echo( "<table id=table class=table>");
echo '<tr  class=Danger><td>Name<td>E-mail';
foreach ($this->users as $user) {
    echo ("<tr>");
    echo("<td  >" . $user['fname'] . " " . $user['lname']);
    echo("<td><a href=".$this->baseUrl()."/user/sendmessage/u_id/". $user['u_id']."/name/". $user['fname']."-".$user['lname'].">Send Message</a>");
    echo(" OR <a href=".$this->baseUrl()."/user/sendmail/email/". $user['email'].">Mail</a>");
}
?>