
<br>

<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
                            
				<li class="active">
					<a href=<?=$this->baseUrl()?>/home>Home</a>
				</li>
                                
                                
                                
			</ul>
                </div>
        </div>
		
</div>
<br><br>
<?php
    echo '<form method=post action='.$this->baseUrl().'/user/signup>';
    echo $this->signUpForm;
    echo '</form>';
?>

<br>
<h5>If you have an account please <a href=<?=$this->baseUrl()?>/user/login>Log In...</a></h5>