

<br>
    
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
                            
                            	<li class="active">
					<a href=<?=$this->baseUrl()?>/categories/list>Home</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/showprofile>Profile</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/choosereceiver>Send Message</a>
				</li>
                                
                                <li class="dropdown pull-right">
					 <a href="/zendapp/public/user/logout" >Log Out</a>
					
				</li>
                                
                                
			</ul>
                </div>
        </div>
		
</div>
<br>


<br><br><br>
<div class="container-fluid" style="float:right;">
	<div class="row-fluid" style="float:right;">
		<div class="span12" style="float:right;">
                    <?php
                        if($this->type==1){
			echo "<ul class=nav nav-list>";
				echo "<li class=nav-header>
					List Options
				</li>
				<li class=active>
					<a href=".$this->baseUrl()."/categories/list>Category</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/forums/list>Forum</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/posts/list>Post</a>
				</li>
				
				<li>
					<a href=".$this->baseUrl()."/comments/list>Comment</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/user/listusers>user</a>
				</li>
			</ul>";
                        }
                     ?>
		</div>
	</div>
</div>
<?php
    //echo "hello";
    echo "<form method=post action=".$this->baseUrl()."/forums/add/categoryId/".$this->catid.">";
    echo "<fieldset >";
    echo "<legend > <font size=6>Add Forum:</font></legend>";
    echo "<font size=4>".$this->forum->f_name."</font><br>";
    echo "<font size=4> <strong> Choose Category: </strong></font><br>";
    echo "&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;";
        echo "<select name=chooseCat style=width:150px;height:30px;>";
        foreach ($this->allCat as $row){
                
                if ($row['c_id']==$this->catid){
                   echo "<option selected value=".$row['c_id'].">".$row['name']."</option>"; 
                }
                else{
                    echo "<option value=".$row['c_id'].">".$row['name']."</option>";
                }
        }
        echo "</select>";
         echo "</br>";
   ?>
<font size="4"> <strong> Choose Lock: </strong></font><br>
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    <select name=chooseLock style="width:150px;height:30px;">
        <option value="unlock">unlock</option>
        <option value="lock">lock</option>
    </select><br>
    <?php
    echo "</fieldset>";
    //echo "&emsp;";
    echo "<font size=5>".$this->forum->submit."</font>";
    echo "</form>";

    ?>
