

<br>
    
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
                            
				<li class="active">
					<a href=<?=$this->baseUrl()?>/categories/list>Home</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/showprofile>Profile</a>
				</li>
                                <li class="active">
					<a href=<?=$this->baseUrl()?>/user/choosereceiver>Send Message</a>
				</li>
                                
                                <li class="dropdown pull-right">
					 <a href="/zendapp/public/user/logout" >Log Out</a>
					
				</li>
                                
                                
			</ul>
                </div>
        </div>
		
</div>
<br>

<br>
<div class="row">
    <div class='col-md-12'>
        <ul class="nav nav-pills">
            <?php
            if ($this->type == 1) {

                // echo "email ".$this->type;
                echo "<li class=active><a href=" . $this->baseUrl() . "/forums/add/catid/" . $this->catid . ">Add Forum</a></li>";
            }
            ?>
        </ul>
    </div>
</div>


<div class="container-fluid" style="float:right;">
	<div class="row-fluid" style="float:right;">
		<div class="span12" style="float:right;">
                    <?php
                        if($this->type==1){
			echo "<ul class=nav nav-list>";
				echo "<li class=nav-header>
					List Options
				</li>
				<li class=active>
					<a href=".$this->baseUrl()."/categories/list>Category</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/forums/list>Forum</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/posts/list>Post</a>
				</li>
				
				<li>
					<a href=".$this->baseUrl()."/comments/list>Comment</a>
				</li>
				<li>
					<a href=".$this->baseUrl()."/user/listusers>user</a>
				</li>
			</ul>";
                        }
                     ?>
		</div>
	</div>
</div>

<?php
 $i=1; 
         echo "<h3> <u> Category Name:</u>&nbsp;&nbsp;&nbsp;".$this->categoryName."</h3>";
            
        echo "<table class=table id=forumTable>";
        echo "<tr class=Danger>";
        echo "<td>forum</td>";
        if($this->type==1){
            echo "<td>edit</td>";
            echo "<td>delete</td>";
        }
        echo "</tr>";
        foreach ($this->forums as $row){
          
           echo "<tr>";
           echo "<td id=n".$row['f_id']."> <a href=http://localhost".$this->baseUrl()."/posts/listsepecific/forumid/".$row['f_id'].">".$row['f_name']."</a> </td>";
           if($this->type==1){
                echo "<td> <a href=".$this->baseUrl()."/forums/edit/forumid/".$row['f_id']."/categoryId/".$row['cat_id']."><img src=".$this->baseUrl()."/images/edit.jpg width=42 height=25></a></td>";
                echo "<td> <a onClick= delet(".$row['f_id'].",".$i.")><img src=".$this->baseUrl()."/images/delete.jpg width=42 height=25></a></td>";
           }
           $i++;
        }
  ?>

 <script>
	var ajaxRequest;
	ajaxRequest=new XMLHttpRequest();

	function delet (id,i){
		var ajaxRequest;
		if (window.XMLHttpRequest){
			ajaxRequest=new XMLHttpRequest();
		}
		else{
			ajaxRequest=new ActiveXObject("Microsoft.XMLHTTP");
		}
		var name;
		name=document.getElementById('n'+id).value;
		ajaxRequest.onreadystatechange=function(){
			if (ajaxRequest.readyState==4){
				document.getElementById("forumTable").deleteRow(i);
			}	
		}
		//var parameters="name="+name+"&id="+id;
		ajaxRequest.open("GET","http://localhost/zendapp/public/forums/delete?forumid="+id, true);
		//ajaxRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		ajaxRequest.send(null);
	
	}
        </script>